`timescale 1ns/1ps
// =================================================================
// tb_cosim.v  –  Co-Simulation Trace Generator for RISC-V CPU
// =================================================================
`include "top.v"

module tb_cosim;

    reg clk;
    reg rst;

    // DUT Taps
    wire [31:0] dbg_pc, dbg_if_instr, dbg_id_instr;
    wire [31:0] dbg_x1,  dbg_x2,  dbg_x3,  dbg_x5,  dbg_x6;
    wire [31:0] dbg_x7,  dbg_x8,  dbg_x9,  dbg_x10, dbg_x11;
    wire [31:0] dbg_x12, dbg_x16, dbg_x17;
    wire [31:0] dbg_dm0, dbg_dm1, dbg_dm2;

    top u_dut (
        .clk          (clk),
        .rst          (rst),
        .dbg_pc       (dbg_pc),
        .dbg_if_instr (dbg_if_instr),
        .dbg_id_instr (dbg_id_instr),
        .dbg_x1       (dbg_x1),  .dbg_x2  (dbg_x2),  .dbg_x3  (dbg_x3),
        .dbg_x5       (dbg_x5),  .dbg_x6  (dbg_x6),  .dbg_x7  (dbg_x7),
        .dbg_x8       (dbg_x8),  .dbg_x9  (dbg_x9),  .dbg_x10 (dbg_x10),
        .dbg_x11      (dbg_x11), .dbg_x12 (dbg_x12), .dbg_x16 (dbg_x16),
        .dbg_x17      (dbg_x17), .dbg_dm0 (dbg_dm0), .dbg_dm1 (dbg_dm1),
        .dbg_dm2      (dbg_dm2)
    );

    // Clock generator: 10 ns period
    always #5 clk = ~clk;

    integer log_file;
    integer k;

    initial begin
        clk = 0;
        rst = 1;
        
        // Load program.hex (generated by Python script)
        $readmemh("program.hex", u_dut.u_imem.mem);

        log_file = $fopen("cpu_trace.log", "w");
        if (log_file == 0) begin
            $display("Error: Could not open cpu_trace.log");
            $finish;
        end

        // Reset Sequence
        #10;
        rst = 1;
        repeat(5) @(posedge clk);
        @(negedge clk); rst = 0;

        // Run simulation for 500 cycles max
        repeat(500) @(posedge clk);
        $fclose(log_file);
        $finish;
    end

    // ── Trace Monitoring Logic ──────────────────────────────────────
    wire [31:0] wb_pc = u_dut.wb_pc_plus4 - 4;
    wire [31:0] mem_pc = u_dut.mem_pc_plus4 - 4;

    always @(posedge clk) begin
        #1; // Wait for pipeline registers to settle
        if (!rst) begin
            // 1. Log Register Writes in Writeback Stage
            if (u_dut.wb_RegWrite && (u_dut.wb_rd != 5'b0) && !u_dut.stall_mem_wb) begin
                $fdisplay(log_file, "x%0d = %h", u_dut.wb_rd, u_dut.wb_write_data);
            end

            // 2. Log Memory Writes in Data Memory or MMIO (only when MEM is not stalled)
            if ((u_dut.u_dmem.MemWrite && !u_dut.stall_ex_mem) ||
                (u_dut.mem_MemWrite && u_dut.is_mmio && !u_dut.stall_ex_mem)) begin
                $fdisplay(log_file, "mem[%h] = %h", u_dut.mem_alu_result, u_dut.mem_write_data);
            end

            // 3. Detect Halt
            if (wb_pc === 32'd220 && !u_dut.stall_mem_wb) begin
                $fdisplay(log_file, "HALT");
                $fclose(log_file);
                $finish;
            end
        end
    end

endmodule
